# Site settings
course_name: Introduction to Machine Learning (CSE 5/474)
course_description: "This course is an introductory course to the field of machine learning. It covers basic concepts, including mathematical underpinnings of standard models as well as the basic skills one needs to begin designing and using ethical machine learning approaches."
course_semester: "Spring 2022"

baseurl: "/cse474" # the subpath of your site, e.g. /blog/
url: "http://kennyjoseph.github.io/" # the base hostname & protocol for your site

schoolname: "University at Buffalo"
schoolurl: "https://cse.buffalo.edu"
twitter_username: _kenny_joseph

address: |
    335 Davis Hall
    Buffalo, NY 14260

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
# google_analytics: UA-XXXXXXXX-X

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
